import os

from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI

from llm.base_llm_runner import BaseLLMRunner


class GeminiLLMRunner(BaseLLMRunner):
    """
    LLM runner for interacting with Google Gemini models.

    Implements the BaseLLMRunner interface and provides a standardized
    run_prompt() method for executing prompts and returning clean responses.
    """

    def __init__(
        self,
        model: str = "models/gemini-2.5-flash",
        api_key: str | None = None,
        temperature: float = 0,
        max_output_tokens: int = 8192,
    ):
        """
        Initialize a Gemini LLM runner.

        Args:
            model: Gemini model identifier.
            api_key: Optional API key override. If not provided, loads
                GOOGLE_API_KEY from the environment.
            temperature: Model temperature.
            max_output_tokens: Maximum tokens generated by Gemini.
        """
        load_dotenv()

        resolved_api_key = api_key or os.getenv("GOOGLE_API_KEY")
        if not resolved_api_key:
            raise ValueError(
                "GOOGLE_API_KEY is missing. Add it to .env or pass api_key."
            )

        self.llm = ChatGoogleGenerativeAI(
            model=model,
            temperature=temperature,
            google_api_key=resolved_api_key,
            max_output_tokens=max_output_tokens,
        )
        self.total_iterations = 0
        self.total_input_tokens = 0
        self.total_output_tokens = 0

    def run_prompt(self, prompt: str) -> str:
        """
        Execute a prompt on the Gemini model and return the raw text response.

        Args:
            prompt: Fully formatted text prompt.

        Returns:
            Cleaned Gemini response content.
        """
        input_tokens = len(prompt) // 4
        self.total_input_tokens += input_tokens
        self.total_iterations += 1

        response = self.llm.invoke(prompt)
        content = response.content.strip()

        output_tokens = len(content) // 4
        self.total_output_tokens += output_tokens

        return content
